### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by baranpirincal** [RomanWuattier/StringsLoader#7]
Hello!

I'm a graphic designer and I like to support open source projects. I would like to design a logo for your project if you interested, I will be happy to work with you! :)

Best Regards

Baran Pirinçal

Graphic Designer

**Comment by RomanWuattier** [comment]
Hey, thanks for your interest
Of course, it would be nice to have a logo!
Feel free to work on it :)

**Comment by baranpirincal** [comment]
@RomanWuattier 

Hey again,

If you have an any idea please feel free to share with me, it would be much better for me :)

**Comment by RomanWuattier** [comment]
The goal of this library is to load strings from a remote/local source. Based on this principle, we can imagine a funny smiley downloading some text.
WDYT?

**Comment by RomanWuattier** [comment]
Closed for inactivity
